services:
  nifi:
    ports:
      - 8443:8443
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=adminadminadmin
    image: apache/nifi:latest
    volumes:
      - nifi_conf:/opt/nifi/nifi-current/conf
      - nifi_flowfile:/opt/nifi/nifi-current/flowfile_repository
      - nifi_content:/opt/nifi/nifi-current/content_repository
      - nifi_provenance:/opt/nifi/nifi-current/provenance_repository
      - nifi_state:/opt/nifi/nifi-current/state
      - nifi_database:/opt/nifi/nifi-current/database_repository

volumes:
  nifi_conf:
  nifi_flowfile:
  nifi_content:
  nifi_provenance:
  nifi_state:
  nifi_database:
